<!DOCTYPE html>
<html lang="id" class="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Printci | Operasional Pembayaran</title>
    @if (! app()->environment('testing') && (file_exists(public_path('build/manifest.json')) || file_exists(public_path('hot'))))
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    @endif
</head>
<body>
<div class="app-shell">
    <aside class="sidebar">
        <a class="brand" href="{{ route('dashboard') }}"><span class="brand-mark">P</span><span>printci<span class="brand-dot">.</span></span></a>
        <div class="workspace-label">RUANG KERJA</div>
        <nav class="nav-list">
            <a class="nav-item active" href="{{ route('dashboard') }}">⌁ Ringkasan</a>
            <a class="nav-item" href="#transaksi">▤ Transaksi <span class="nav-count">{{ $stats['today'] }}</span></a>
            <a class="nav-item" href="#pelanggan">◉ Pelanggan</a>
            <a class="nav-item" href="#template">▧ Template struk</a>
            <a class="nav-item" href="#printer">⌗ Perangkat printer</a>
        </nav>
        <div class="sidebar-bottom"><div class="connection-card"><span class="status-pulse"></span><div><strong>Ruang kerja lokal</strong><small>Semua sistem berjalan normal</small></div></div><div class="profile"><div class="avatar">AD</div><div><strong>Admin Demo</strong><small>Pemilik ruang kerja</small></div></div></div>
    </aside>
    <main class="main-content">
        <header class="topbar"><div><p class="eyebrow" id="realtime-clock">Memuat waktu...</p><h1><span id="realtime-greeting">Selamat datang</span>, Admin <span class="wave">✦</span></h1></div><button class="avatar avatar-small">AD</button></header>
        @if(session('success'))<div class="toast">{{ session('success') }} <span>✓</span></div>@endif
        <section class="hero-row"><div><h2>Operasional pembayaran</h2><p>Semua pembayaran Anda terpantau dalam satu tempat.</p></div><div class="hero-actions"><a class="button button-ghost" href="{{ route('transactions.export') }}">⇩ <span>Ekspor data</span></a><button class="button button-primary" data-open="scan-modal">＋ <span>Transaksi baru</span></button></div></section>
        <section class="stat-grid"><article class="stat-card"><div class="stat-icon indigo">↗</div><div><span>Transaksi hari ini</span><strong>{{ number_format($stats['today']) }}</strong><small class="trend up">+12,5% <em>dari kemarin</em></small></div></article><article class="stat-card"><div class="stat-icon mint">◆</div><div><span>Pendapatan hari ini</span><strong>Rp {{ number_format($stats['revenue'], 0, ',', '.') }}</strong><small class="trend up">+8,2% <em>dari kemarin</em></small></div></article><article class="stat-card"><div class="stat-icon amber">◷</div><div><span>Menunggu ditinjau</span><strong>{{ number_format($stats['pending']) }}</strong><small class="trend neutral">Perlu perhatian</small></div></article><article class="stat-card"><div class="stat-icon blue">✓</div><div><span>Struk tercetak</span><strong>{{ number_format($stats['printed']) }}</strong><small class="trend up">98,7% <em>tingkat berhasil</em></small></div></article></section>
        <section class="content-grid"><div class="panel transactions-panel" id="transaksi"><div class="panel-heading"><div><h3>Transaksi terbaru</h3><p>Tinjau, cetak, dan kelola pembayaran terbaru.</p></div></div><div class="table-toolbar"><div class="search-box">⌕ <input type="search" placeholder="Cari transaksi..." data-table-search></div><select class="select-control"><option>Semua status</option><option>Lunas</option><option>Draf</option><option>Dibatalkan</option></select></div><div class="table-wrap"><table><thead><tr><th>Transaksi</th><th>Pelanggan</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>@forelse($transactions as $transaction)<tr data-table-row><td><strong>{{ $transaction->invoice_number }}</strong><small>{{ $transaction->created_at->format('d M Y, H:i') }}</small></td><td>{{ $transaction->customer?->name ?? $transaction->sender_name ?? 'Pelanggan umum' }}</td><td><strong>Rp {{ number_format($transaction->total_amount ?: $transaction->amount, 0, ',', '.') }}</strong></td><td><span class="status {{ $transaction->status }}"><i></i>{{ ['paid' => 'Lunas', 'draft' => 'Draf', 'void' => 'Dibatalkan'][$transaction->status] ?? ucfirst($transaction->status) }}</span></td><td><div class="row-actions"><a href="{{ route('transactions.receipt', $transaction) }}" target="_blank" title="Buka struk">↗</a><form method="POST" action="{{ route('transactions.reprint', $transaction) }}">@csrf<button title="Cetak ulang">⎙</button></form></div></td></tr>@empty<tr><td colspan="5" class="empty-state">Belum ada transaksi. Scan bukti pembayaran pertama Anda.</td></tr>@endforelse</tbody></table></div>{{ $transactions->links() }}</div><div class="side-stack"><div class="panel printer-panel" id="printer"><div class="panel-heading"><div><h3>Perangkat printer</h3><p>Koneksi Bluetooth dari browser</p></div><span class="live-dot">Aktif</span></div>@forelse($printers as $printer)<div class="device-row"><div class="printer-glyph">⌗</div><div class="device-info"><strong>{{ $printer->name }}</strong><small>{{ $printer->paper_size }} · {{ $printer->status === 'online' ? 'Terhubung' : 'Belum terhubung' }}</small></div></div><button class="button button-connect" data-connect-printer data-printer-id="{{ $printer->id }}">⌁ <span>Hubungkan printer</span></button>@empty<p class="muted-copy">Belum ada printer terdaftar.</p>@endforelse</div><div class="panel quick-panel" id="template"><h3>Penyiapan cepat</h3><p>Ruang kerja, kategori, dan template sudah siap.</p><div class="setup-bar"><span style="width:75%"></span></div></div></div></section>
        <section class="lower-grid"><div class="panel scan-panel" id="pelanggan"><div class="scan-copy"><span class="section-kicker">PEMINDAIAN CERDAS</span><h3>Scan bukti pembayaran</h3><p>Unggah tangkapan layar transfer. Data pembayaran dan biaya admin akan dihitung otomatis.</p><button class="button button-primary" data-open="scan-modal">▣ <span>Scan bukti baru</span></button></div></div><div class="panel category-panel"><div class="panel-heading"><div><h3>Kategori pembayaran</h3><p>Berdasarkan jumlah transaksi</p></div></div>@foreach($categories->take(4) as $category)<div class="category-row"><span class="category-dot" style="background:{{ $category->color }}"></span><strong>{{ $category->name }}</strong><span class="category-count">{{ $category->transactions()->count() }} transaksi</span></div>@endforeach</div></section>
        <section class="management-grid" id="management"><div class="panel management-card"><span class="section-kicker">DIREKTORI</span><h3>Kelola pelanggan</h3><form method="POST" action="{{ route('management.customer') }}" class="inline-form">@csrf<input name="name" placeholder="Nama pelanggan" required><input name="phone" placeholder="Nomor telepon"><select name="segment"><option>Reguler</option><option>Setia</option><option>VIP</option></select><button class="button button-primary">＋ Tambah</button></form></div><div class="panel management-card"><span class="section-kicker">STRUK</span><h3>Template struk</h3><form method="POST" action="{{ route('management.template') }}" class="inline-form">@csrf<input name="name" placeholder="Nama template" required><select name="paper_size"><option>58mm</option><option>80mm</option></select><select name="font_size"><option value="normal">Huruf normal</option><option value="small">Huruf kecil</option><option value="large">Huruf besar</option></select><input name="header" placeholder="Teks kepala struk"><input name="footer" placeholder="Teks kaki struk"><button class="button button-primary">＋ Simpan</button></form></div><div class="panel management-card"><span class="section-kicker">KATALOG</span><h3>Kategori pembayaran</h3><form method="POST" action="{{ route('management.category') }}" class="inline-form">@csrf<input name="name" placeholder="Nama kategori" required><input name="color" value="#818cf8" required><input name="icon" value="wallet" required><button class="button button-primary">＋ Tambah</button></form></div><div class="panel management-card"><span class="section-kicker">PERANGKAT</span><h3>Daftarkan printer</h3><form method="POST" action="{{ route('management.printer') }}" class="inline-form">@csrf<input name="name" placeholder="Nama printer" required><input name="bluetooth_id" placeholder="ID Bluetooth"><select name="paper_size"><option>58mm</option><option>80mm</option></select><button class="button button-primary">＋ Daftarkan</button></form></div></section>
    </main>
</div>
<div class="modal-backdrop" id="scan-modal"><div class="modal"><button class="modal-close" data-close="scan-modal">×</button><div class="modal-heading"><span class="modal-icon">⌁</span><div><span class="section-kicker">PEMINDAIAN CERDAS</span><h3>Transaksi pembayaran baru</h3><p>Tambahkan foto untuk mengisi data otomatis.</p></div></div><form method="POST" action="{{ route('transactions.store') }}" enctype="multipart/form-data" class="transaction-form">@csrf<div class="upload-zone" id="proof-zone"><input type="file" name="proof" accept="image/*" id="proof-input"><label for="proof-input"><span>⇧</span><strong>Letakkan foto bukti pembayaran di sini</strong><small>PNG atau JPG maksimal 5MB</small></label><div class="proof-added" id="proof-added" hidden><img id="proof-preview" alt="Pratinjau bukti pembayaran"><div><strong id="proof-name">Bukti pembayaran</strong><small id="proof-status">Foto berhasil ditambahkan.</small></div><button type="button" id="proof-change">Ganti foto</button></div></div><div class="form-grid"><label>Nominal pembayaran<input type="number" name="amount" id="payment-amount" min="0" step="0.01" placeholder="0" required></label><label>Waktu pembayaran<input type="datetime-local" name="paid_at" value="{{ now()->format('Y-m-d\\TH:i') }}"></label><label>Nama pengirim<input type="text" name="sender_name" placeholder="Nama dari bukti transfer"></label><label>Bank tujuan<input type="text" name="destination_bank" placeholder="Bank tujuan"></label><label>ID transaksi<input type="text" name="transaction_id" placeholder="ID dari bukti transfer"></label><label>Pelanggan<select name="customer_id"><option value="">Pelanggan umum</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }}</option>@endforeach</select></label><label>Kategori pembayaran<select name="payment_category_id">@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label><label>Template struk<select name="receipt_template_id">@foreach($templates as $template)<option value="{{ $template->id }}">{{ $template->name }} · {{ $template->paper_size }}</option>@endforeach</select></label></div><div class="fee-summary"><span>Nominal pembayaran <strong id="summary-amount">Rp 0</strong></span><span>Biaya admin <strong>Rp 2.500</strong></span><span class="fee-total">Total dibayar <strong id="summary-total">Rp 2.500</strong></span></div><div class="modal-footer"><span class="ocr-note">✦ Foto ditambahkan. Data OCR dapat disunting.</span><button type="button" class="button button-ghost" data-close="scan-modal">Batal</button><button class="button button-primary" type="submit">Simpan transaksi <span>→</span></button></div></form></div></div>
</body>
</html>
